#!/bin/sh

REQUIRED_NAME="liminal-loop"
ACTUAL_NAME="$(git config --get user.name)"

if [ "$ACTUAL_NAME" != "$REQUIRED_NAME" ]; then
  echo "Commit blocked: git user.name must be '$REQUIRED_NAME' for this repository."
  echo "Current user.name: '${ACTUAL_NAME:-<unset>}'"
  echo "Run: git config --local user.name $REQUIRED_NAME"
  exit 1
fi

exit 0
